server:
  port: 8080

#包中文件日志等级
logging:
  level:
    com:
      myself:
        mapper: debug
        service: info
        controller: info

spring:
  profiles:
    active: dev
#  解决循环依赖，ioc容器中的
  main:
    allow-circular-references: true
  datasource:
    druid:
      username: ${cangqiong.datasource.username}
      password: ${cangqiong.datasource.password}
      url: jdbc:mysql://${cangqiong.datasource.host}:${cangqiong.datasource.port}/${cangqiong.datasource.database}?${cangqiong.datasource.other}
      driver-class-name: ${cangqiong.datasource.driver-class-name}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: entity

cangqiong:
  jwt:
#    jwt过期时间
    admin-expire-time: 7200000
#    jwt的token名字
    admin-token-name: token
#    jw密钥
    admin-secret-key: ranle


