server:
  port: 8080


logging:
  level:
    root: info

spring:
  profiles:
    active: dev
#  结局循环依赖，ioc容器中的
  main:
    allow-circular-references: true
  datasource:
    druid:
      username: ${cangqiong.datasource.username}
      password: ${cangqiong.datasource.password}
      url: jdbc:mysql://${cangqiong.datasource.host}:${cangqiong.datasource.port}/${cangqiong.datasource.database}?${cangqiong.datasource.other}
      driver-class-name: ${cangqiong.datasource.driver-class-name}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: entity
